export const type = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_ONE: "REMOVE_ONE",
  SET_USER: "SET_USER",
  SET_AUTH_LOADING: "SET_AUTH_LOADING",
  EMPTY_CART: "EMPTY_CART",
};
